## -*- encoding: utf-8 -*-
## This file (main.sagetex.sage) was *autogenerated* from main.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('main', version='2020/08/12 v3.5', version_check=True)
